### ISSUE TITLE
`org-noter-auto-save-last-location` bug/incomplete feature

### ISSUE THREAD

**Issue by petermao** [org-noter/org-noter#12]
Setting `org-noter-auto-save-last-location` to `non-nil` implies that when starting org-noter, the document opens to the last location saved in the notes file.  This works when opening the session from the notes file, but not when opening the file from the document.  Particularly irritating is when I open a session from Dired with `org-noter-start-from-dired`.
`org-noter` (the command) needs to check for the saved location and set the document to that location early in the startup process.
I will take this on, but if someone else gets to it before me, more power to them!

**Comment by dmitrym0** [comment]
I didn't know this was a thing! Thanks Peter 👍
