### ISSUE TITLE
Allow notes file to be specified when opening publications

### ISSUE THREAD

**Issue by dmitrym0** [org-noter/org-noter#15]
I'd like to be able to specify where the notes for a publication go. This is primarily to separate notes by topic in an org-roam environment.

I envision something like so:

1. open a pdf file (via dired, or directly)
2. invoke `M-x org-noter`
3. invoke a hook (if defined) that returns a filename where notes are to be created.
4. open org-noter in that document

If there's no hook, we fall through to the current behaviour 

Structurally, there's nothing preventing this functionality. I can create an empty file, paste an org-noter property drawer there, invoke org-noter and it'll work fine:

```
* DevOps uses a capability model, not a maturity model
:PROPERTIES:
:NOTER_DOCUMENT: pubs/devops-capability.pdf
:END:
```

The goal is to avoid manual work of copying/pasting the org-noter header.

**Comment by petermao** [comment]
Doesn't this already exist as `org-noter-notes-search-path` in conjunction with `org-noter-default-notes-file-names`?  Depending on your specific workflow, you may need to make the second one `nil`, but that also may have undesirable side effects.

**Comment by petermao** [comment]
My config uses the default settings, but I typically keep a `Notes.org` file in the dir with the papers.  In that case, starting an org-noter session adds an entry into that file.  It also happens if it's higher up in the path.

NOT using `Notes.org` as your default file in combination with judicious use of `M-n` may already give you what you want.

**Comment by dmitrym0** [comment]
I'm thinking about a completing-read interface so when you invoke org-noter you can narrow to where notes go.. I've seen noter ask me about this but I haven't explored how it works yet. I suppose this is similar to what was being asked in #2.

**Comment by dmitrym0** [comment]
This is the same as #16, closing this one.
