### ISSUE TITLE
two old commits slow down org-noter

### ISSUE THREAD

**Issue by ckeschnat** [org-noter/org-noter#17]
I think my straight.el switched to this repo only recently and I was using a very old version of org-noter before. Hence a report on old commits. 

With the current version, every action in org-noter (e.g. next page) takes about 8 seconds on my machine. 
I used git bisect to look for the issue and actually found two changes that slow down org-noter:

The first one is https://github.com/org-noter/org-noter/commit/49bc6ee2ecfc12445d4483550215b887080c9c06 
With the commit before that (f38f313), every action (e.g. next page) is instant.
On this commit, every action takes about 2 seconds.

The next one is https://github.com/org-noter/org-noter/commit/f74263f0e19f205d7ffe2f0bc230a01d5a814128
This slows org-noter down from about 2 seconds to 8 seconds.

As it seems to be working for others, I suspect this might also be related to my org mode settings? I did not yet try with default settings (will do that later) but still wanted to report - maybe someone immediately sees an issue with those commits.

Thank you

**Comment by petermao** [comment]
Does the org noter you are running include this commit: cd3c86c?

I've seen the problem before and I thought I fixed it.  I'm on vacation this week, so I won't fully engage with this until next week.  In the meantime, take a look at that commit and see which side of it your are on.

**Comment by ckeschnat** [comment]
PS: Just saw the above comment while I was writing this one and doing more profiling. But I'll save this comment now and try the linked basic test.

I checked out the latest version again - there is no `org-collect-keywords` anywhere.

I tried some more profiling[1] and these functions seem to be slow (the number is seconds):

org-noter--doc-location-change-handler 3.4634544016
org-noter--get-view-info 3.4546647738
org-noter--doc-goto-location 7.801248251
org-noter-pdf-goto-location 7.580284689


[1] With elp http://stardiviner.github.io/Blog/Emacs-slow-and-heavy-Profile,-Benchmark-your-Emacs,-and-speed-it-up.html

**Comment by ckeschnat** [comment]
> I'm not seeing the slow down you're speaking of. Maybe https://github.com/org-noter/org-noter-with-emacs-basic-test could be of use. It spawns an emacs process in a sandbox but with org-noter installed.

Ok, no problems with this and both are on the same commit (a24ba82). So it must be something with my configuration. 

I think this can then be closed and I will try to find out what's going on on my machine (will report in case I find anything).

Thank you for your help.

**Comment by dmitrym0** [comment]
Well that's one data point. Keep us updated if it's something in org-noter. Feel free to re-open if you wish.

**Comment by ckeschnat** [comment]
Found it (somewhat).

I noticed that the sandbox used org 9.5.5 (5b300ed).
I use org 9.6.1 (e46811c5e) (I'm not sure why, straight just installed this version).

So, I used straight.el's `versions/default.el` to downgrade my version to 9.5.5 and org-noter works as expected.

I don't know how to try org 9.6 with the sandbox to test it.

There might be something here https://github.com/radian-software/straight.el#how-do-i-pin-package-versions-or-use-only-tagged-releases but maybe you know how to do it?

**Comment by ckeschnat** [comment]
That got me 9.7-pre (release_9.6.30-313-g5b300e) and then there were two directories, `org` and `org-mode` and the package was built on every `eval-buffer`. Not sure what happens there.

Anyways, `(use-package org)` gave me 9.6.1.

`org-noter` is still fast. 

So, versions seem compatible. Back to searching in my config.

**Comment by ckeschnat** [comment]
Found it.

`(require 'org-inlinetask)` -> after this, `org-noter` is slow.

I had added this snippet recently:
https://kitchingroup.cheme.cmu.edu/blog/2017/04/09/A-better-return-in-org-mode/
