### ISSUE TITLE
Cannot create note

### ISSUE THREAD

**Issue by quigonjeff** [org-noter/org-noter#21]
Hi.

Recently org-noter started giving me an error message every time I try to create a note. Something like this:

`listp: Wrong type argument: listp, #s(org-noter-pdftools--location "pdf:~/Library/Calibre Library/Timothy Williamson/Modal Logic As Metaphysics (993)/Modal Logic As Metaphysics - Timothy Williamson.pdf" 11 7.51 nil nil "pdf:~/Library/Calibre Library/Timothy Williamson/Modal Logic As Metaphysics (993)/Modal Logic As Metaphysics - Timothy Williamson.pdf::11++7.51")`

Does anybody has some advice of how to fix it?

**Comment by petermao** [comment]
This is a problem with org-noter-pdftools becoming an unmaintained package for about a year now.

See https://github.com/fuxialexander/org-pdftools/issues/93#issuecomment-1493314118 and https://github.com/fuxialexander/org-pdftools/pull/94
