### ISSUE TITLE
Setting up highlighting

### ISSUE THREAD

**Issue by encomun** [org-noter/org-noter#28]
I am having trouble getting highlight to work. In the readme, C-u is supposed to toggle highlighting, but I just get the message "Beginning of buffer."

I am a beginner with emacs and don't really know elisp. I tried adding the highlighting hook this way:

 (add-hook 'org-noter-add-highlight-hook 'org-noter-doc-mode)

But that didnt' seem to work. What should I add to my init file to make highlighting the pdf the default behavior?

**Comment by petermao** [comment]
Not enough info to go on here.  Can you give a rundown of what you do to get the "Beginning of buffer" message?  I assume it starts with selecting some text in the document.

Are you highlighting a pdf?  Are you using pdf-tools?  The hook you're adding to is meant for the modules to set up.

C-u <insert command> should be sufficient. If you want it on all the time, then customize the variable `org-noter-highlight-selected-text`.

**Comment by encomun** [comment]
Yes, sorry. Highlighting a pdf using pdftools. After selecting text, C-u would give the "Beginning of buffer" message and a note command afterwards wouldn't result in the text highlighted.

(setq org-noter-highlight-selected-text t) worked for me. Thanks for making that clear.

**Comment by petermao** [comment]
> [...] After selecting text, C-u would give the "Beginning of buffer" message

I can't reproduce this behavior in a pure vanilla session, so I suspect there's something in your config that's tweaking the `C-u` prefix.  Did you check what `C-u` is bound to (with `C-h c C-u`)?  Normally, that would be `universal argument`.  I suspect your config has it bound elsewhere.

**Comment by encomun** [comment]
You're right, C-u is bound to the evil-scroll-up command for me.

But I always want org noter to highlight so the org-noter-highlight-selected-text works great for me.

Thanks for your assistance.

**Comment by petermao** [comment]
@dmitrym0: I pushed cd93b9e to update the README.  no code changes.
