### ISSUE TITLE
Performance issues with org 9.6.x, 9.7-pre

### ISSUE THREAD

**Issue by petermao** [org-noter/org-noter#29]
I just tried out Emacs 29.0.91 which includes with Org 9.6.5.  Org-noter is **very** slow with this setup.  We will need to figure out what changed and how we can get reasonable performance back.

**Comment by petermao** [comment]
Ran some tests tonight on Moby Dick.  We're back to the situation where the timing code runs fast on the first execution, and then takes about 30x longer on subsequent runs.  Also, the first run takes about 2x the time that Emacs 28/Org 9.5 takes to run the timing code, so we have, potentially a 60x hit, which makes for poor user experience.

**Comment by petermao** [comment]
New to Org 9.6: https://orgmode.org/Changes.html (line 378, if you use `eww`)

maybe it's time to (re) replace `org-element-map` with  `org-element-cache-map`

**Comment by dmitrym0** [comment]
Can you remind -- last time was it an org issue? 

If so we should be able to isolate it to a test case.

**Comment by petermao** [comment]
I fixed it last time with commit cd3c86c by removing uses of `org-collect-keywords`.  When I profile note navigation in https://github.com/org-noter/org-noter/blob/cd93b9e294699b9d05eb75f62d931f49a7d9b878/tests/Notes.org#L403 it looks to me like `org-element-map` could be the culprit, but if I recall correctly, that was what I thought last time, too, and I had to bisect the code by hand to fix it.

It would be nice to have a test that reports back a navigation through Moby Dick's skeleton.

**Comment by petermao** [comment]
There are a bunch of calls to `org-element-map` that have `lambda`s for their mapping functions.  We'll need to pull these out as named functions so that we can support both `org-element-map` and `org-element-cache-map`, since the former may be slowing down this package in Org 9.6 and the latter doesn't exist in Org 9.5.

### Here's the catalog for reference:

`org-noter--show-note-entry`
https://github.com/org-noter/org-noter/blob/aa6d3d24fcbfbc2daa9721a79df3f003c51d285e/org-noter-core.el#L1365-L1374

`org-noter--get-view-info`
https://github.com/org-noter/org-noter/blob/aa6d3d24fcbfbc2daa9721a79df3f003c51d285e/org-noter-core.el#L1516-L1594

`org-noter--make-view-info-for-single-note`
https://github.com/org-noter/org-noter/blob/aa6d3d24fcbfbc2daa9721a79df3f003c51d285e/org-noter-core.el#L1610-L1616

`org-noter-insert-note` (two calls!)
https://github.com/org-noter/org-noter/blob/aa6d3d24fcbfbc2daa9721a79df3f003c51d285e/org-noter-core.el#L2115-L2120  https://github.com/org-noter/org-noter/blob/aa6d3d24fcbfbc2daa9721a79df3f003c51d285e/org-noter-core.el#L2155-L2157

`org-noter--map-ignore-headings-with-doc-file` (macro)
https://github.com/org-noter/org-noter/blob/aa6d3d24fcbfbc2daa9721a79df3f003c51d285e/org-noter-core.el#L2236-L2248

**Comment by dmitrym0** [comment]
> since the former may be slowing down this package in Org 9.6 and the latter doesn't exist in Org 9.5.

Have you confirmed that `org-element-map` is the culprit? I quick and dirty way might be to mass-replace `org-element-map` -> `cache-map` and see if it's still slow?

This also raises the question of backwards compatibility..should we support org 9.5 if this is indeed the issue?

**Comment by petermao** [comment]
No, I haven't fully convinced myself that it is `org-element-map`.  I'd like to document the issue a bit more and get some help from the community to debug this one.

`map` and `cache-map` are a bit different, so it's not obvious right now how to implement the `cache-map` variant.

I'd like to pull the lambdas out, since it's harder to see from the profiler which calls to `map` are the slow ones, but in my first attempt, things go haywire.  I'll try to get a PR rolling by Friday.

**Comment by dmitrym0** [comment]
Gotcha, don't rush on my account. I'm behind on everything.

**Comment by larrasket** [comment]
@petermao can you point out a version that this issue does not occure with? I downgraded to `Org mode version 9.5.3 (9.5.3-??-69c5889 @ /home/l/.emacs.d/.local/straight/build-29.1.50/org/)` but still suffering. Here is my profile with it:
```
                                                                      11569  99% - command-execute
                                                                      11217  96%  - funcall-interactively
                                                                      11213  96%   - pdf-view-next-line-or-next-page
                                                                      11211  96%    - pdf-view-next-page
                                                                      11211  96%     - pdf-view-goto-page
                                                                      11055  94%      - org-noter--doc-location-change-handler
                                                                      11018  94%       - org-noter--get-view-info
                                                                      10999  94%        - org-element-map
                                                                      10999  94%         - #<compiled -0x16d24b4277cb5987>
                                                                      10999  94%          - mapc
                                                                      10999  94%           + #<compiled -0x16d24b4277cb5987>
```
It's significantly better than other version so i'm not really sure if is it the default of org-noter. I can tell that pdf-view itself is very fast if compared.

**Comment by petermao** [comment]
As I mentioned above, the Org 9.5.x that comes built into Emacs 28.2 would run acceptably fast.  I haven't been able to pin down exactly what in Org 9.6.x is slowing down the code.

**Comment by larrasket** [comment]
It's also acceptable in my case, but once there are a bigger number of notes (about 10 notes) it start to get very slow when switching from pages. same with epub but when switching between chapters

**Comment by petermao** [comment]
@larrasket if you've cloned this repo, try opening up Moby Dick in the `tests` subdir and running the timing test.  I got ~10.5 seconds under emacs 28.2 and with 29.1, it now takes 28.5 sec.

**Comment by larrasket** [comment]
I did test it and it was extremly slow, not sure how much time tho. I solved the issue by downgrading to `9ead81d42dd4dd5074782d239b2efddf9b8b7b3d` (I picked it up arbitrarily). It's possible that the issue is coming from my workflow instead.

**Comment by petermao** [comment]
the timing code in the Notes file there under Moby Dick reports the time in the output.

**Comment by larrasket** [comment]
Oh how stupid, I thought that I'd test the against the org file instead by hand. I will report the test when I get back.

**Comment by petermao** [comment]
I did some git-bisection on Org-mode today, using the timing code in tests/Notes.org (Moby Dick, "Title page" heading).  This test starts from the title page and navigates through the skeleton of the file (each chapter + epilogue) and back up, 138 steps in each direction.

```
| org version/commit | time to nav Moby Dick |
|                    |                   [s] |
|--------------------+-----------------------|
| releaase_9.5.5     |                  18.8 |
| releaase_9.6.6     |                  24.0 |
| releaase_9.6.8     |                  24.2 |
| f4446ce79          |                  24.3 |
| f4aa3747e          |                  28.0 |
| 4d63e571e          |                  29.8 |
| 3b1693c46          |                  52.8 |
| 7cbc44191          |                  >200 |

**Comment by yantar92** [comment]
Peter Mao ***@***.***> writes:

> I did some git-bisection on Org-mode today, using the timing code in tests/Notes.org (Moby Dick, "Title page" heading).  This test starts from the title page and navigates through the skeleton of the file (each chapter + epilogue) and back up, 138 steps in each direction.

It would help if you provide full profiler report (M-x
profiler-report-write-profile) or describe how to reproduce for someone
not familiar with org-noter.

-- 
Ihor Radchenko // yantar92,
Org mode contributor,
Learn more about Org mode at <https://orgmode.org/>.
Support Org development at <https://liberapay.com/org-mode>,
or support my work at <https://liberapay.com/yantar92>

**Comment by petermao** [comment]
I'll generate the profiler reports, but I also need to write up the procedure for the timing test.  It seems to be highly dependent on setup.  Anecdotally, I started emacs from the org-mode repo yesterday with `make vanilla`,  got pdf-tools and org-noter loaded, and ran the Moby Dick test.  It was **much** faster than my other tests.  sub 12 seconds with Emacs 29.1/Org 9.6.8.  Looks like I'll have to rerun the table above with the new procedure.

**Comment by petermao** [comment]
ugh.  I can't reproduce the org-mode `make vanilla` results. It would be great to do this in one test script, but I haven't figured that out yet.

**Comment by petermao** [comment]
I wrote a bash script and init file to set up the Moby Dick speed test:
https://github.com/org-noter/org-noter-with-emacs-basic-test/tree/speed-test#speed-test-with-moby-dick

This doesn't use the `with-emacs` package, but it does set up a vanilla session with `pdf-tools` and `org-mode` installed from your local repos.  Hopefully this will improve reproducibility.

**Comment by yantar92** [comment]
Dmitry ***@***.***> writes:

> I'm a little hazy on the details: does `-Q` guarantee that nothing is read or written to `.emacs`?

Yes. And more than that - nothing is also read from system-wide
site-lisp, if you installed some Emacs packages via your OS package
manager:

              -Q, --quick
                      Similar to "-q --no-site-file --no-splash".  Also, avoid
                      processing X resources.

              -q, --no-init-file
                      Do not load an init file.

              --no-site-file
                      Do not load the site-wide startup file.

              --no-splash
                      Do not display a splash screen during start-up.


-- 
Ihor Radchenko // yantar92,
Org mode contributor,
Learn more about Org mode at <https://orgmode.org/>.
Support Org development at <https://liberapay.com/org-mode>,
or support my work at <https://liberapay.com/yantar92>

**Comment by petermao** [comment]
I just pushed new code here (on the `master` branch) and on the `speed-test` branch of `org-noter-with-emacs...`

The main new feature is that the profiler reports are saved with the `emacs-version`, `org-git-version`, and elapsed time encoded in the filenames.

@yantar92, is this sufficient for you to run some timing tests on your side?  I can run the tests on my side and post the profiler files, but I don't yet know what I'm looking for in those files.  In general, I'm finding that old-Org runs faster than new-Org, old-Emacs runs faster than new-Emacs, and the seconds run of the test code-block is always 2-3 seconds faster than the first one.

**Comment by petermao** [comment]
New repo dedicated to the speed test: https://github.com/org-noter/org-noter-speed-test.

This should make it easier for anyone to set up and run the test.

**Comment by yantar92** [comment]
Peter Mao ***@***.***> writes:

> @yantar92, is this sufficient for you to run some timing tests on your
> side?

No, unfortunately. Cask does not work on my OS and I thus cannot install
pdf-tools in the way speed-test tries to.

> ...I can run the tests on my side and post the profiler files, but I
> don't yet know what I'm looking for in those files. In general, I'm
> finding that old-Org runs faster than new-Org, old-Emacs runs faster
> than new-Emacs, and the seconds run of the test code-block is always
> 2-3 seconds faster than the first one.

I am looking for the files produced by M-x profiler-report-write-profile.

-- 
Ihor Radchenko // yantar92,
Org mode contributor,
Learn more about Org mode at <https://orgmode.org/>.
Support Org development at <https://liberapay.com/org-mode>,
or support my work at <https://liberapay.com/yantar92>

**Comment by petermao** [comment]
> I am looking for the files produced by M-x profiler-report-write-profile.

OK, I will push a bunch of speed-test results to that repo.

**Comment by petermao** [comment]
I was just looking into issue #48 with the lastest org-noter.  I'm getting decent speed (~15-16 sec) on the first run of the speed test all the way up to the latest Org mode (9.7-pre, 9.6.8-post).  Also no navigation errors.

New profiler files also pushed to org-noter-speed-test repo.

**Comment by yantar92** [comment]
> New profiler files also pushed to org-noter-speed-test repo.

I looked into a few random profiler from that repo, and they look like command execution was interrupted with C-g, making the profiles unreadable.

**Comment by petermao** [comment]
> I looked into a few random profiler from that repo, and they look like command execution was interrupted with C-g, making the profiles unreadable.

Strange -- they are all scripted from the org-babel elisp code block: https://github.com/org-noter/org-noter/blob/9d42ebc626981b6736b8078fb216b30cc5e34d21/tests/Notes.org?plain=1#L438-L447

Am I calling `profiler-stop` incorrectly?

**Comment by petermao** [comment]
I, too, am at a loss on how to interpret these profiler reports.  They look different every time I run them.

**Comment by yantar92** [comment]
Peter Mao ***@***.***> writes:

> I, too, am at a loss on how to interpret these profiler reports.  They look different every time I run them.

You might want to report this as Emacs bug, which it probably is.

To get useful results, I would try to fall back to manual checking
instead of automated.

-- 
Ihor Radchenko // yantar92,
Org mode contributor,
Learn more about Org mode at <https://orgmode.org/>.
Support Org development at <https://liberapay.com/org-mode>,
or support my work at <https://liberapay.com/yantar92>

**Comment by petermao** [comment]
> You might want to report this as Emacs bug, which it probably is.

I think I'll need to come up with a more minimal example first.  This would be a pretty big mess to drop on the maintainers.

Manual checking is tough because the whole point of  that code block is to generate repeatable speed tests and to try to identify what's slowing the code down.
