### ISSUE TITLE
Inserting Note fails with wrog number of arguments

### ISSUE THREAD

**Issue by uliw** [org-noter/org-noter#3]
I recently started to have the following problem:

- Inserting a new a note using M-i creates the error message below. Ctrl-i Tab works as expected as long as the area marked in the pdf is no longer than a single line. 

```
org-noter--get-precise-info: Wrong number of arguments: (lambda (mode) "Get precise info from MODE." (if (eq mode 'pdf-view-mode) (progn (let ((org-pdftools-free-pointer-icon org-noter-pdftools-free-pointer-icon) (org-pdftools-free-pointer-color org-noter-pdftools-free-pointer-color) (org-pdftools-free-pointer-opacity org-noter-pdftools-free-pointer-opacity) (org-pdftools-markup-pointer-color org-noter-pdftools-markup-pointer-color) (org-pdftools-markup-pointer-opacity org-noter-pdftools-markup-pointer-opacity) (org-pdftools-markup-pointer-function org-noter-pdftools-markup-pointer-function)) (org-noter-pdftools--parse-link (org-pdftools-get-link)))))), 2
```

- inserting a note via i, results in this error

```
org-noter-pdf--pretty-print-location-for-title: Wrong type argument: listp, #s(org-noter-pdftools--location "pdf:~/user/papers_to_read/wolf-gladrow-2007-total-alkal.pdf" 1 0.0 "annot-1-7" nil "pdf:~/user/papers_to_read/wolf-gladrow-2007-total-alkal.pdf::1++0.00;;annot-1-7")
```

**Comment by dmitrym0** [comment]
Hi @uliw,

Can you confirm the version of org-noter you're using? 

`Get precise info from MODE` does not appear in org-noter at all.

**Comment by petermao** [comment]
Try a clean install of the latest version, and run it with `emacs -Q` so we know that your `init.el` isn't the source of the problem.  If you're still having problems, please include a stripped down copy of the noter tree for this document.  It helps us to see what the property drawers look like.

**Comment by uliw** [comment]
ok, fresh install with minimal startup file (attached below) running `emacs -q -l settings-min.el`
Results in the same error. 

Dropping a pdf file on emacs, and then calling org-noter, results in the following file content (which appears to be correct)
```
* Sulfur isotopes in rivers: insights into global weathering budgets, pyrite oxidation, and the modern sulfur cycle
:PROPERTIES:
:NOTER_DOCUMENT: ~/Documents/papers_to_read/burke-2018-sulfur-isotop-river.pdf
:Custom_ID: burke-2018-sulfur-isotop-river
:URL: http://dx.doi.org/10.1016/j.epsl.2018.05.022
:AUTHOR: Burke, A., Present, T. M., Paris, G., Rae, E. C., Sandilands, B. H., J\'erôme Gaillardet, Peucker-Ehrenbrink, B., …
:END:
```

emacs version is `
GNU Emacs 28.2 (build 1, x86_64-suse-linux-gnu, GTK+ Version 3.24.35, cairo version 1.17.6)`

[settings-min.zip](https://github.com/org-noter/org-noter/files/11043900/settings-min.zip)

**Comment by petermao** [comment]
I think @fuxialexander is actively maintaining that repo, so he should be able to fix the issue for you.

**Comment by rdiaz02** [comment]
But this is an issue that has been introduced with the recent changes in org-noter: this does not happen with org-noter 1.4.1.  So  the changes break existing functionality in other packages.

**Comment by lazzalazza** [comment]
Hi, the issue seems to be closed but no correction has apparently been proposed. I have a functioning workaround:

`;; Added patch function
(defun org-noter--check-and-convert-location (location)
  "If the location is an org-noter-pdftools-location, it transforms it into a (page . height) cons, otherwise it keeps the cons unaltered"
  (interactive)
  (if (org-noter-pdftools--location-p location)
      (cons (org-noter-pdftools--location-page location)
            (org-noter-pdftools--location-height location))
    location))
`

also, line 2262 should be changed in: "(org-noter--pretty-print-location-for-title (org-noter--check-and-convert-location location))"

**Comment by dmitrym0** [comment]
@lazzalazza are you sure you're running latest of org-noter and org-noter-pdftools?

**Comment by lazzalazza** [comment]
@dmitrym0 yep, I had updated everything: does it work fine for you?
org-noter-pdftools-20230725.1433
org-noter-20231205.37

Am I missing something? Has a function that converts `org-noter-pdftools--location` to the cons used by org-noter been introduced? My solution actually took org-noter-pdftools in consideration, because the issue was felt by those who use that package and not simply org-noter.

**Comment by lazzalazza** [comment]
@dmitrym0 I'm trying to use the `org-noter--pretty-print-location-for-title-hook` to apply the `org-noter--check-and-convert-location` function from within org-noter-pdftools.el file, but I can't figure out a way to do that: would that be a possible way to go?

**Comment by dmitrym0** [comment]
Could this be an issue with org-noter-pdftools?

normally you can ‘require’ an elisp module to get at its functions.

**Comment by lazzalazza** [comment]
@dmitrym0 I wouldn't say so, the problem is that when I try to implement something like that from within the org-noter-pdfools package I have troubles making the function check the location without tampering with the result...

```
 (defun org-noter--check-and-convert-location (location)
  "If the location is an org-noter-pdftools-location, it transforms
it into a (page . height) cons, otherwise it keeps the cons
unaltered"
  (if (org-noter-pdftools--location-p location)
      (cons (org-noter-pdftools--location-page location)
            (org-noter-pdftools--location-height location))
    location))

(add-hook 'org-noter--pretty-print-location-for-title-hook
          'org-noter--check-and-convert-location)
```
I don't know if this is useful, but here is what the debugger sais:

```
Debugger entered--Lisp error: (invalid-function (125 . 0.86))
  (125 . 0.86)("$p$")
  replace-regexp-in-string("\\$p\\$" (125 . 0.86) "Notes for page $p$")
  org-noter-insert-note(nil #s(org-noter-pdftools--location :path "pdf:~/Dropbox/Autori/Marini/Opere/Marini - settima..." :page 125 :height 0.86 :annot-id "annot-125-8" :search-string nil :original-property "pdf:~/Dropbox/Autori/Marini/Opere/Marini - settima..."))
  org-noter-insert-precise-note(nil)
  funcall-interactively(org-noter-insert-precise-note nil)
  command-execute(org-noter-insert-precise-note)
```

**Comment by dmitrym0** [comment]
Looking at the stack trace and at the [emacs manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Search-and-Replace.html) 2nd parameter to `replace-regexp-in-string` is expected to either be a string or a function, but your code seems to be passing in a `cons`. 

I don't use org-noter-pdftools so I don't know what's going on here.
