### ISSUE TITLE
PDFView fit width does not work with org-noter split fraction

### ISSUE THREAD

**Issue by gnohz** [org-noter/org-noter#30]
I have the following:
`(setq pdf-view-display-size 'fit-width)
(setq org-noter-doc-split-fraction '(0.6 . 0.4))
`
It seems only the later (split-fraction) works, but the former (fit-width) does not.

**Comment by petermao** [comment]
Formally, this is not an Org-noter issue, but I think I can answer your question.

If you want `pdf-view-display-size` to be persistent, you need to set it with `M-x customize-variable ...`.  As the documentation indicates (`C-h v pdf-view-display-size`), "Automatically becomes buffer-local when set."  This means that where ever you ran that `setq`, the variable is only set in that buffer.

**Comment by gnohz** [comment]
> Formally, this is not an Org-noter issue, but I think I can answer your question.
> 
> If you want `pdf-view-display-size` to be persistent, you need to set it with `M-x customize-variable ...`. As the documentation indicates (`C-h v pdf-view-display-size`), "Automatically becomes buffer-local when set." This means that where ever you ran that `setq`, the variable is only set in that buffer.

Yes, you are right. 
It is just weird that I cannot change the value even using "M-x customize-variable". Btw, I am using Doom.

**Comment by petermao** [comment]
The standard advice, which applies in this case, is to verify features and behavior with `emacs -Q` and then bisect your config.
