### ISSUE TITLE
`org-noter-insert-note` complains, `valign--flag-region-advice: Args out of range: 194, 519`

### ISSUE THREAD

**Issue by stewmehr** [org-noter/org-noter#35]
### Description

This is a duplicate of [issue 148 in the original repo](https://github.com/weirdNox/org-noter/issues/148) - I am not the user who originally raised it but am seeing similar behaviour (same error, same workaround that fixes it).

#### Steps to Reproduce

1. Load Emacs
2. Open a pdf document
3. Run M-x org-noter
4. hit `i` (`org-noter-insert-note`)

#### Expected Results

org-noter opens

#### Actual Results

org-noter does not open with message `valign--flag-region-advice: Args out of range: 194, 519`

Adding the following advice to `outline-show-entry` fixes the issue but I have not really sussed out why that is:
```elisp
    (defun my/outline-show-entry ()
      "Show the body directly following this heading.
Show the heading too, if it is currently invisible."
      (interactive)
      (save-excursion
        (outline-back-to-heading t)
        (outline-flag-region (max (1- (point)) (point-min))
                             (progn
                               (outline-next-preface)
                               (if (= 1 (- (point-max) (point)))
                                   (point-max)
                                 (point)))
                             nil)))
    (advice-add 'outline-show-entry :override #'my/outline-show-entry)
```

### Environment

Org mode version 9.7-pre (release_9.6.5-377-gfe74a3
Emacs version 28.2

**Comment by dmitrym0** [comment]
The advice in the error message seems to come from this package: https://github.com/casouri/valign/blob/master/valign.el

Do you have it installed by any chance?

**Comment by stewmehr** [comment]
Huh, yes indeed, purely for cosmetics (it makes org-tables look fancy). It never occurred to me that the advice snippet from above may be part of a package because I never searched for it. I can also confirm that disabling `valign` makes the problem disappear. I take it that this is a bug caused by `valign` messing with `point-min` and `point-max` then?

**Comment by dmitrym0** [comment]
>I take it that this is a bug caused by `valign` messing with `point-min` and `point-max` then?

Difficult to say what's going on, without actually looking at the code. Sure seems that way.  

~Interesting that the bug is 2 years old but hasn't been identified in valign~ -- scratch that, I just looked in valign's repo and here's a similar (identical?) issue: https://github.com/casouri/valign/issues/23

**Comment by petermao** [comment]
This appears to be outside of our problem-field.  Can we close this issue?

**Comment by stewmehr** [comment]
Yes, of course! I'll try and find a fix for this on the `valign` repo.
