### ISSUE TITLE
Arrows and highlights no longer displayed

### ISSUE THREAD

**Issue by stewmehr** [org-noter/org-noter#38]
#### Steps to Reproduce

1. Load Emacs
2. Open a pdf document that already has a notes file
3. Run M-x org-noter
4. Cycle through notes via `org-noter-sync-{next|previous}-note`
5. Pdf document pages update (so syncing is not affected) but no arrow and/or highlights appear. ~~The page is just blank.~~

#### Expected Results

I would like to get my little arrow back and get marked regions highlighted in yellow.

#### Actual Results

No arrow is displayed, highlighted sections are no longer highlighted.

Unfortunately I cannot say when this issue first appeared. I initially thought that my problem had something to do with `pdf-tools` but annotating pdfs outside of an `org-noter` session still works as expected.

### Environment

Org version: 9.7-pre
Emacs version: 28.2

**Comment by dmitrym0** [comment]
> The page is just blank.

Does the contents of the pdf document appear?

**Comment by petermao** [comment]
Can you try it with Org 9.5?  I'm seeing problems with 9.6 and you're ahead of that.

Are you using org-noter-pdftools?  that package needs maintenance TLC, which it's not currently getting.

**Comment by stewmehr** [comment]
@dmitrym0 Thanks for the swift reply and sorry for the ambiguous description. No, the pdf displays just fine, all that is missing is the arrow and the highlights. This is odd because it used to work just fine on my end. I have recently picked up `org-noter` again to do some reading and now the arrows are gone.

@petermao Thank you as well. I have switched to using built-in org-mode  9.5.5 and the issue persists. I am not using `org-noter-pdftools`, no.

**Comment by stewmehr** [comment]
Update/correction: the arrow is not gone completely! It is just not displayed properly (see screenshot [1]). I failed to see that sooner because most of my "precise notes" in the PDF below are located at the beginning of the line. Hence, `org-noter-arrow-horizontal-offset` moved the dark placeholder blip that I currently see instead of the red arrow further to the left, on top of the dark background of the theme I am using (see screenshot [2]).

[1]: Red arrow on page replaced by dark blip.
<img width="1680" alt="Screenshot 2023-05-31 at 09 14 40" src="https://github.com/org-noter/org-noter/assets/62615938/2bcfad19-8444-401c-9e81-d3ef073b6152">

[2]: Dark blip on top of dark background:
<img width="1680" alt="Screenshot 2023-05-31 at 09 30 41" src="https://github.com/org-noter/org-noter/assets/62615938/ae7bf391-a4f5-43e2-a2a8-cb34cf8f3d69">

**Comment by petermao** [comment]
Please try it with `emacs -Q`.  I'm 95% confident it's something in your config that you'll need to bisect.

**Comment by stewmehr** [comment]
> I'm 95% confident it's something in your config

... well, so was I. Alas, I have cut my `init.el` down to the few dozen lines below and the issue persists. I run emacs via `emacs -Q -load init-bugfix.el` and there ist still no arrows to be seen. I probably should mention that I am on macOS.

As I have compiled my emacs from source I will do a fresh pull and rebuild it tomorrow. In the meantime, if you have any other suggestions or questions, I'm all ears 🙂 

<details><summary>Config snippet <code>init-bugfix.el</code></summary>
```elisp
(defvar bootstrap-version)
(let ((bootstrap-file (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent
         'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
(straight-use-package 'use-package)

(use-package emacs
  :custom
  (straight-use-package-by-default t))

(use-package org
  :straight
  (:type built-in))

(use-package pdf-tools
  :mode
  (("\\.pdf\\'" . pdf-view-mode))
  :config
  (pdf-tools-install))

(use-package org-noter
  :straight
  (:repo "org-noter/org-noter"
   :host github
   :type git
   :files ("*.el" "modules/*.el"))
  :custom
  (org-noter-notes-window-location 'horizontal-split)
  (org-noter-arrow-foreground-color "orange red")
  (org-noter-insert-note-no-questions nil)
  (org-noter-auto-save-last-location t))
```
</details>

**Comment by petermao** [comment]
Try this: https://github.com/org-noter/org-noter-with-emacs-basic-test

We use it to test the code before mergine PRs.  You'll need to pull your own copy of org-noter.  To make your life easy, put it in `~/workspace/org-noter`, otherwise, you'll need to deal with the tricky part mentioned below.

Follow the instructions in the README to a "T".  The only tricky part (I hope it's the only one) is that when the emacs window opens, you may need to edit the path to your local copy of org-noter (unless you put it in `~/workspace/org-noter`.

OSX has many variants of emacs on it.  When I'm on a Mac, I run Emacs under XQuartz with no problems.  I can't say anything about the other variants.  I think @dmitrym0 uses OSX, too.  Not sure which one he uses.

**Comment by stewmehr** [comment]
I can confirm that my issue persists in in the test environment:
<img width="1680" alt="Screenshot 2023-06-03 at 12 12 35" src="https://github.com/org-noter/org-noter/assets/62615938/91f2fb4a-6629-4c79-9a97-a2bdb50e3bdc">

I am now in the process of rebuilding emacs with the following flags at the configuration stage:
`./configure --with-cairo --with-imagemagick --with-xwidgets --with-native-compilation`. Are there any other tests you would like me to run?

**Comment by petermao** [comment]
No other tests I can think of.  I don't think this has anything to do with the code in `org-noter`, so you are correct to look at rebuilding your emacs.

An easier test for you may be to open a pdf in a frame, split the frame and then put this code in the other frame:
```
(progn
  (other-window 1)
  (pdf-util-tooltip-arrow 0.5))
```
You should see a tooltip arrow show up half-way down the left side of the pdf page.

**Comment by stewmehr** [comment]
That last test pointed me in the correct direction. I did not read the `org-noter` sources attentively enough, otherwise I would have known that displaying the org-noter arrow makes use of `pdf-util-tooltip-arrow`. It appears that this is an [upstream issue with `pdf-tools`](https://github.com/vedang/pdf-tools/issues/175) which has already been reported. Thank you for your help and for letting me check out `with-emacs.sh` (have you heard of chemacs as well?), will be closing this issue now.

**Comment by petermao** [comment]
@stewmehr, thanks for the update.
