### ISSUE TITLE
visual-line-mode doesn't work in the org notes buffer

### ISSUE THREAD

**Issue by ugurbolat** [org-noter/org-noter#45]
### Description

when entered into org-noter mode, visual-line-mode doesn't work in the org notes buffer are even though visual-line-mode is enabled

#### Steps to Reproduce

My Config:

```
(use-package! org-noter
  :after (:any org pdf-view)
  :config
  (setq org-noter-always-create-frame nil
        org-noter-notes-window-behavior '(start)
        org-noter-notes-window-location 'other-frame
        org-noter-notes-search-path `(,ub/zk-bib-notes-dir)
        org-noter-auto-save-last-location t
        org-noter-default-notes-file-names '("000_org_noter.org")))
```

#### Expected Results

`visual-line-mode` should be respected 

#### Actual Results

![org-noter](https://github.com/org-noter/org-noter/assets/9626688/79e5f4be-2f74-4834-9c39-01f220a211e2)

### Environment
Ubuntu 22.04, Emacs 28.2

### Note

I've also tried to create the following hook to enforce it but no success:

```
(defun my-enable-visual-line-mode ()
  (visual-line-mode 1)
  (setq-local truncate-lines nil))

(add-hook 'org-noter-notes-mode-hook 'my-enable-visual-line-mode)
```

**Comment by petermao** [comment]
I was not able to reproduce this behavior running in an instance set up via https://github.com/org-noter/org-noter-with-emacs-basic-test.

I ran with this part of your config (leaving out the path/filename choices):
```
(setq org-noter-always-create-frame nil
      org-noter-notes-window-behavior '(start)
      org-noter-notes-window-location 'other-frame
      org-noter-auto-save-last-location t)
```

I started visual line mode with `M-x visual-line-mode` and the text wrapped in the expected manner.  This is likely to be a problem introduced by your config or some other package you have installed.

**Comment by ugurbolat** [comment]
Thanks for the response! 

I didn't know that you provided a way to test with vanilla emacs. Nice!

I have spinned up edebug to go through "org-noter--create-session", but haven't managed to see something related yet...

Do you have any ideas on how to debug this issue?

**Comment by petermao** [comment]
The problem does not lie in the `org-noter` code base because visual line mode works with the sandboxed version.

I suggest starting from `emacs -q` or starting from the sandboxed version mentioned above, then bisect your config file -- run `M-x eval-region` on the first half of it and see if `visual-line-mode` works, then repeat at 1/4 if it doesn't work, or 3/4 if it does.   Lather, rinse, repeat.  Eventually, you'll find the thing in your config that's breaking the feature.

**Comment by rgri** [comment]
Hi @ugurbolat. I am experiencing this issue too, and have noticed that you probably were using DOOM at the time of this issue's creation. Do you happen to remember what was the cause of the problem?

**Comment by ckeschnat** [comment]
Culprit for me was:
`(setq org-startup-indented t)`

**Comment by dmitrym0** [comment]
> From [weirdNox#44 (comment)](https://github.com/weirdNox/org-noter/issues/44#issuecomment-726730596)
> 
> ```emacs-lisp
> (defun my/no-op (&rest args))
> (advice-add 'org-noter--set-notes-scroll :override 'my/no-op)
> ```
> 
> This fixes it without needing to disable org-indent-mode. @dmitrym0 can the fix be included into the package? I think indent mode is the default for doom, and probably spacemacs.

Trying to understand the issue here to come up with a good fix. Looks like an interplay between `indent-mode` somehow?  How does `org-noter--set-notes-scroll` factor into it?

**Comment by petermao** [comment]
I still can't reproduce this, though I don't use doom or spacemacs.

Turned on org indent as a `+=STARTUP:` directive.  visual-line-mode works as expected.

Personally, I don't use indent.  Tried it for a while and found it to be more trouble than it was worth with org-babel code blocks.
