### ISSUE TITLE
Option to disable "ATTENTION: org-noter-nov" and "org-noter-dvju"

### ISSUE THREAD

**Issue by rdiaz02** [org-noter/org-noter#5]
I am getting

```
ATTENTION: org-noter-nov needs the package ‘nov’.
ATTENTION: org-noter-dvju needs the package ‘djvu’.

```
And that is triggered even by a minimal loading of the package as

```
(require 'package)
(package-initialize)

(require 'org-noter)
```

Is there a way to disable them for those of us who do not need to use `org-noter-nov`  or `org-noter-dvju`?

**Comment by petermao** [comment]
Customize your `org-noter-supported-modes`.  In your case, remove `nov-mode ` and `djvu-read-mode`.

**Comment by rdiaz02** [comment]
> Customize your `org-noter-supported-modes`, which controls which of the three available modules (pdf, nov, djvu) get loaded. In your case, remove `nov-mode ` and `djvu-read-mode`.
> 

Thanks a lot. (And sorry for the noise; I looked over the variables I could customize and I obviously missed that).

> The detection of the supporting modes is done by `(assq '<package-name> package-alist)` in the module's `.el` file. Note that this is just an informational message. If you never use nov or djvu, it won't matter that those packages are not installed.

Yes, that code I saw, and I understand the message is informational and the lack of packages (and the message itself) innocuous, but I'd rather keep the start-up messages to those things that require my attention. So customizing `org-noter-supported-modes` works great here.

Thanks again. Closing as solved.
