### ISSUE TITLE
Automatically adding `org-pdftools` links to annotations?

### ISSUE THREAD

**Issue by ghost** [org-noter/org-noter#50]
It seems to be possible to create precise links to pdftools buffers with org-pdftools. Would it make sense to automatically add those links for created annotations? Then just visiting the org buffer would be enough for jumping wherever those annotations are pointing to.

**Comment by petermao** [comment]
Org-pdftools has not been touched by its owner since March 2022.  There are some incompatibilities between `org-noter` and `org-pdftools` since @dmitrym0 and I took over maintainership (see Issues #6, #7, and #8).

Given that neither @dmitrym0 or I use `org-pdftools` or `org-noter-pdftools`, we would be hard-pressed to take up the time to grok and integrate that code base, and then do the necessary lobbying to take over maintainership.

**Comment by lockywolf** [comment]
I see.

I am still thinking that integration would have been a good thing, so I might have a look at it myself.

Also, org-pdftools doesn't seem to be that huge, so perhaps it would be possible to just gradually migrate the code from org-pdftools to org-noter, reducing function duplication in process?

I do think that a good note-taking program is very important, so I might have a look at it myself, but I am not sure when that might be.

**Comment by petermao** [comment]
org-pdftools maintainer just merged 2 PRs yesterday (7/25).  I think if you install both this package and that one, you'll have what you want.  LMK how that works for you.

**Comment by lockywolf** [comment]
Okay, org-noter-pdftools in fact only exposes the following functions to the user:

1. `org-noter-pdftools-convert-old-org-heading`
2. `org-noter-pdftools-convert-old-notes`
3. `org-noter-pdftools-jump-to-note`
4. `org-noter-pdftools-create-skeleton` (this function is very-very similar to `org-noter-pdf--create-skeleton`
5. `org-noter-pdftools-embed-org-note-to-pdf` 
6. `org-noter-pdftools-embed-all-org-note-to-pdf`
7. `org-noter-pdftools-embed-org-buffer-to-pdf`

of which skeleton creation is almost the same as in org-noter, and legacy notes are probably not very useful. So the only useful functions are the `*embed*` family.

**Comment by lockywolf** [comment]
Ah, so the `*embed*` functions are now in the org-noter itself https://github.com/org-noter/org-noter/commit/d42a28009a7ef2a5e49a10372bb619073e4da517 

I guess org-noter-pdftools is now not useful any more?

**Comment by lockywolf** [comment]
Sorry, I am confused. 

Is there anything in the suggested version of org-noter-pdftools'

```
(defun org-noter-pdftools-insert-precise-note (&optional toggle-no-questions)
    (interactive "P")
    (org-noter--with-valid-session
     (let ((org-noter-insert-note-no-questions (if toggle-no-questions
                                                   (not org-noter-insert-note-no-questions)
                                                 org-noter-insert-note-no-questions))
           (org-pdftools-use-isearch-link t)
           (org-pdftools-use-freepointer-annot t))
       (org-noter-insert-note (org-noter--get-precise-info)))))
```

which the now updated `org-noter-pdftools-insert-precise-note` cannot do?

**Comment by petermao** [comment]
The code in org-noter that I recently brought up-to concurrency with org-pdftools was just an exercise to understand the provenance and recent changes to that code base.  If you want that functionality, install org-pdftools.  The code in org-noter does not ship with the package, and there are no "hooks" into from org-noter.

**Comment by lockywolf** [comment]
I mean, that package is just 700 lines, of which  only 300 are user-facing. 
Moreover, `org-noter` now uses `pdf-tools` itself, which means that functions from that package can be adopted, while reducing duplication, painlessly.

The key thing in org-noter-pdftools is, seemingly, not the "org-pdftools" links, at least at the first glance.  I will try to see if some functions from that package can be painlessly merged into org-noter, if you do not mind.

**Comment by petermao** [comment]
As you wish; however, given that `org-pdftools` is under active maintainership, I think it would be best for @fuxialexander to have a say in it.

If you make the PR, we will look at it and discuss.

**Comment by petermao** [comment]
closing as OP has disappeared.
