### ISSUE TITLE
Page number as a note property

### ISSUE THREAD

**Issue by DaviRaubach** [org-noter/org-noter#51]
Hi mantainers,

Some time ago, I asked for page number and quotation marks on notes extracted from the document and I was very happy that you did that. Thank you. 

Now, sometimes I am replacing the default "Notes for page p. ___ V: __% H: __%". 

I thought we could have the page number in a property.

Example:

``` org-mode
** Notes for page p. 355 V: 26% H: 7%
:PROPERTIES:
:NOTER_PAGE: (2 0.26049204052098407 . 0.07260726072607263)
:PAGE_NUMBER: 355
:END:
```

Thanks

**Comment by petermao** [comment]
In the example you give, the title would be "Notes for page 2 V: 26% H: 7%".  Are you asking for the page number in the title to be the pdf page label ("355" in this case)?  Do you also need the page label as a property of the entry?

**Comment by DaviRaubach** [comment]
> In the example you give, the title would be "Notes for page 2 V: 26% H: 7%"

Actually, it added automatically the title, including “p. 355”. I didn't edit it. Maybe because it is the actual page label. See in Mac PDF viewer:

![Captura de Tela 2023-07-26 às 09 14 45](https://github.com/org-noter/org-noter/assets/37299137/ebf9d52d-d72d-4d32-8f39-eb9d4c3ec046)

> Are you asking for the page number in the title to be the pdf page label ("355" in this case)?

No. In this case, it already is. But, generally, I will replace the title anyway to be more descriptive. 

> Do you also need the page label as a property of the entry?

Yes. 

Some PDFs have the pages labeled correctly, so it would be easy to just put it on a property. Others go, for example, from page 100-110 and are labeled 1-10. In this last case, I think the interface could ask for the first page number and then calculate the entries `PAGE_NUMBER` property.

**Comment by petermao** [comment]
So there is a "page number" and a "page label" in PDFs.  For locating the note in the document, we use the "page number", which is the number you see in the NOTER_PAGE property.   The "page label" is used in the default title.  By default, the "page label" corresponds with the "page number," but in books with frontmatter (often labelled with lowercase roman numberals), the arabic numbering doesn't start until later in the book.

The rationalle for using "page label" in the title is that if you needed to communicate the location of the note to someone without org-noter, you would refer to the page label, rather than the ordinal numbering in your copy of the document.  For you, the org-noter user, the page number is encoded in the properties already, and org-noter will bring you to the desired location in your document.

In your example above, I assume we are looking at the second page of the PDF (page number = 2) which carries a page label "355," but in your initial noter entry example, you have PAGE_NUMBER: 355.  I still don't have a clear idea of what you want and need, likely owing to the inconsistent nomenclature.  My guess is that you want the "page label" as a stored property, but I'd like to know how that would improve org-noter.

**Comment by DaviRaubach** [comment]
My initial example was intended to suggest a note format after implementing the idea.

Thinking more about it, I realized I had 2 ideas:

### 1) Extract the page label and add it as a property

The modified note format would look like this:
```
*** Informative title
:PROPERTIES:
:NOTER_PAGE: (19 0.123094958968347 . 0.15686274509803919)
:NOTER_PAGE_LABEL: "p. 372"
:END:
```
Advantage: This way, users can give the note any title they desire without worrying about annotating the page.

### 2) Ask for the first page number, calculate the page for each note, add it as a property
The modified note format would look like this:
```
*** Descriptive title
:PROPERTIES:
:NOTER_PAGE: (19 0.123094958968347 . 0.15686274509803919)
:NOTER_CALCULATED_PAGE: 119
:NOTER_PAGE_LABEL: "CXIX"
:END:
```

Advantages: flexibility in note titling and the ability to handle PDF documents with varying page numbering conventions.


I asked chatGPT some help to describe the second idea:

I would like to request a customization in the behavior of org-noter to enhance its usability for academic work, particularly in handling PDF files with incorrect page numbers. 

Currently, when initializing org-noter and specifying the path to the document, it would be beneficial if org-noter prompted the user to enter the number of the first page in the document. With this information, org-noter can intelligently calculate and adjust the subsequent page numbers for note-taking.

For example, during the initialization process, after requesting the path to the document, org-noter could prompt the user with the following question: “Please enter the number of the first page in the document:”. The user would then input the correct page number, taking into account any discrepancies with the page labeling in the PDF file.

Using this information, org-noter could accurately calculate the page numbers for subsequent notes. For instance, if the user enters 100 as the first page number and the note refers to page number 19, org-noter would calculate the page number for this note as 100 + 19 (the relative page number of the note) = 119.

The modified note format would look like this:

```
*** Descriptive title
:PROPERTIES:
:NOTER_PAGE_LABEL: "CXIX"
:NOTER_PAGE: (19 0.123094958968347 . 0.15686274509803919)
:NOTER_CALCULATED_PAGE: 119
:END:
```

By implementing this feature, org-noter can provide a seamless and efficient solution for handling PDF documents with inconsistent page numbering, enhancing the usability of the tool for academic purposes.

Thank you for considering this enhancement for org-noter.

--

Just an idea... Check if it is interesting.

**Comment by petermao** [comment]
At this point, this is unlikely be be implemented in org-noter by me or @dmitrym0.  You can implement it for yourself as a hook function or advice to one of org-noter's functions.  We can help you out with that by pointing out the relevant functions and variables.  Dmritry has some advice that he runs in his custom setup that may be adapted for your use.

**Comment by petermao** [comment]
[This test](https://github.com/org-noter/org-noter/blob/master/tests/org-noter-extra-tests.el) has code that modifies the behavior or `org-noter-insert-note`, but it may not match up cleanly with what you want to do.

Another option is to add your custom function to `org-noter-insert-note-hooks`.  Your hook function must take no arguments, so you should use `org-noter-with-valid-session` and make use of `-session-doc-buffer` and `-session-notes-buffer`.

I'm assuming you are familiar with elisp, but if not, don't hesitate to reach out.
