### ISSUE TITLE
Consider not narrowing the org buffer by default.

### ISSUE THREAD

**Issue by lockywolf** [org-noter/org-noter#55]
#### Steps to Reproduce

1. Open a pdf file
2. Run `org-noter`

#### Expected Results

org-file with notes is opened

#### Actual Results

org-file with notes is opened and narrowed to a subtree

### Environment

org 9.6.6, emacs 30.0.50

### Comment

Narrowing an org buffer is a dangerous thing. I suspect that under no normal circumstances packages should call narrowing themselves, as narrowing is so low-level that the result will almost always not be what you want.

In the worst case, it is better to create an indirect buffer, and do all org data extrating operations there, presumably, with (save-restriction (save-excursion ... )) , but with an indirect buffer it would not be so important.

**Comment by petermao** [comment]
I believe this is how we received the package when we took over maintenance.  Personally, I keep one Notes.org file per directory, pointing to (typically) 10-100 documents.  I have not had any problems with the narrowing.  There may be an option to bypass the narrowing, but I'm not sure.

Unless there is breakage of the code and/or inordinate hue and cry from the user-base, we are unlikely to alter the default behavior of `org-noter`.

**Comment by petermao** [comment]
I have confirmed that `(setq org-noter-disable-narrowing t)` has the desired effect, so I am closing this issue.  The default wil remain `nil`.
