### ISSUE TITLE
`org-noter-pdftools-create-skeleton` and `org-noter-pdf--create-skeleton` are painfully similar.

### ISSUE THREAD

**Issue by lockywolf** [org-noter/org-noter#56]
### Description

In the most recent org-noter, `org-noter-pdf--create-skeleton` and `org-noter-pdftools-create-skeleton` are doing almost entirely the same thing. Consider removing one of those?

**Comment by petermao** [comment]
The `org-noter-pdftools` is not part of the org-noter package.  The code in inherited from the original `org-noter` repo, and I simply updated it recently for "academic" purposes.
