### ISSUE TITLE
Use `org-before-first-heading-p` in org-noter--parse-root

### ISSUE THREAD

**Issue by dmitrym0** [org-noter/org-noter#58]
From #48 

>Side note: In org-noter--parse-root,
>
>    (save-excursion
>       (goto-char (point-min))
>       (eq 'property-drawer (org-element-type (org-element-at-point)))))
>
>is not reliable - first line may not be top-level property drawer. It might also be a comment. You can instead use `org-before-first-heading-p`.

**Comment by petermao** [comment]
The code in question first appears in commit d2cd744 by @c1-g and takes its present form in 0ab97959.

I agree that it is fragile.  The fix would require that we start at point-min and step down in the buffer until we see a property drawer or `org-before-first-heading-p` returns nil.

I wonder how many users set `org-noter-prefer-root-as-file-level` to `t`?  I don't, so I've never seen the problem.

**Comment by petermao** [comment]
So this part of `--parse-root` only gets called when org-noter is initializing a session, which makes sense, given the claim to grab file-level properties.

I'll just note that this function gets called **9 times** on initialization and **4 times** for every `-sync-next/prev-note`!  I'm not sure what the differences are between all the calls, but this may be a place where we can speed up the code.
