### ISSUE TITLE
outline-before-first-heading error when adding a heading after file-level property drawer

### ISSUE THREAD

**Issue by svictor9** [org-noter/org-noter#59]
#### Steps to Reproduce
1. Create an empty file
2. run org-noter and select a pdf file to annotate. Org-noter sets a file-level property drawer.
3. create a headline (not necessarily an org-noter one) beneath the property drawer
4. end the org-noter session
5. restart the org-noter session

Org-noter fails to stard with error (outline-before-first-heading)

Here are the contents of my file:
```
:PROPERTIES:
:NOTER_DOCUMENT: /home/vic/bib/pdfs/Dessertine.pdf
:END:

* and a headline
```

Setting `org-noter-prefer-root-as-file-level` to t makes no difference.  

#### Backtrace
With point at `(point-min)`, on the property drawer, I get this
```
Debugger entered--Lisp error: (outline-before-first-heading)
  signal(outline-before-first-heading nil)
  org-narrow-to-subtree()
  org-noter--narrow-to-root((section (:begin 1 :end 72 :contents-begin 1 :contents-end 71 :robust-begin 1 :robust-end 69 :post-blank 1 :post-affiliated 1 :mode first-section :granularity greater-element :cached t :parent (org-data (:begin 1 :contents-begin 1 :contents-end 88 :end 88 :robust-begin 70 :robust-end 86 :post-blank 0 :post-affiliated 1 :path "/home/vic/ordis/tests/org-noter-test.org" :mode org-data :NOTER_DOCUMENT "/home/vic/bib/pdfs/Dessertine.pdf" :CATEGORY "org-noter-test" :granularity greater-element) #1 (headline (:raw-value "and a headline" :begin 72 :end 88 :pre-blank 0 :contents-begin nil :contents-end nil :robust-begin nil :robust-end nil :level 1 :priority nil :tags nil :todo-keyword nil :todo-type nil :post-blank 0 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 72 :title "and a headline" :mode nil :granularity element :cached t :parent #27)))) (property-drawer (:begin 1 :end 72 :contents-begin 14 :contents-end 65 :post-blank 1 :post-affiliated 1 :mode top-comment :granularity element :cached t :parent #1))))
  org-noter--setup-windows(#s(org-noter--session :id 465622726476747901 :frame #<frame Emacs Org-noter - Dessertine.pdf 0x55cbcb2f1fa8> :doc-buffer #<buffer Dessertine.pdf> :notes-buffer #<buffer Notes of Dessertine.pdf> :ast (section (:begin 1 :end 72 :contents-begin 1 :contents-end 71 :robust-begin 1 :robust-end 69 :post-blank 1 :post-affiliated 1 :mode first-section :granularity greater-element :cached t :parent (org-data (:begin 1 :contents-begin 1 :contents-end 88 :end 88 :robust-begin 70 :robust-end 86 :post-blank 0 :post-affiliated 1 :path "/home/vic/ordis/tests/org-noter-test.org" :mode org-data :NOTER_DOCUMENT "/home/vic/bib/pdfs/Dessertine.pdf" :CATEGORY "org-noter-test" :granularity greater-element) #2 (headline (:raw-value "and a headline" :begin 72 :end 88 :pre-blank 0 :contents-begin nil :contents-end nil :robust-begin nil :robust-end nil :level 1 :priority nil :tags nil :todo-keyword nil :todo-type nil :post-blank 0 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 72 :title "and a headline" :mode nil :granularity element :cached t :parent #28)))) (property-drawer (:begin 1 :end 72 :contents-begin 14 :contents-end 65 :post-blank 1 :post-affiliated 1 :mode top-comment :granularity element :cached t :parent #2))) :modified-tick 460 :doc-mode pdf-view-mode :display-name "Dessertine.pdf" :notes-file-path "/home/vic/ordis/tests/org-noter-test.org" :property-text "/home/vic/bib/pdfs/Dessertine.pdf" :level 0 :num-notes-in-view nil :window-behavior (start scroll) :window-location horizontal-split :doc-split-fraction (0.5 . 0.5) :auto-save-last-location nil :hide-other nil :closest-tipping-point 0.3))
  #f(compiled-function () #<bytecode -0x1b2c44441c553369>)()
  apply(#f(compiled-function () #<bytecode -0x1b2c44441c553369>) nil)
  timer-event-handler([t 0 0 50000 nil #f(compiled-function () #<bytecode -0x1b2c44441c553369>) nil idle 0 nil])
```

With point after the headline, I get this other error
```
Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  org-noter--narrow-to-root((headline (:raw-value "and a headline" :begin 72 :end 89 :pre-blank 0 :contents-begin nil :contents-end nil :robust-begin nil :robust-end nil :level 1 :priority nil :tags nil :todo-keyword nil :todo-type nil :post-blank 0 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 72 :title "and a headline" :mode first-section :granularity greater-element :parent (org-data (:begin 1 :contents-begin 1 :contents-end 89 :end 89 :robust-begin 70 :robust-end 87 :post-blank 0 :post-affiliated 1 :path "/home/vic/ordis/org-noter-property-drawer-bug.org" :mode org-data :NOTER_DOCUMENT "/home/vic/bib/pdfs/Dessertine.pdf" :CATEGORY "org-noter-property-drawer-bug" :granularity greater-element) #1))))
  org-noter--setup-windows(#s(org-noter--session :id 772898809900936324 :frame #<frame Emacs Org-noter - and a headline 0x55bc13d0ff38> :doc-buffer #<buffer Dessertine.pdf> :notes-buffer #<buffer Notes of and a headline> :ast (headline (:raw-value "and a headline" :begin 72 :end 89 :pre-blank 0 :contents-begin nil :contents-end nil :robust-begin nil :robust-end nil :level 1 :priority nil :tags nil :todo-keyword nil :todo-type nil :post-blank 0 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 72 :title "and a headline" :mode first-section :granularity greater-element :parent (org-data (:begin 1 :contents-begin 1 :contents-end 89 :end 89 :robust-begin 70 :robust-end 87 :post-blank 0 :post-affiliated 1 :path "/home/vic/ordis/org-noter-property-drawer-bug.org" :mode org-data :NOTER_DOCUMENT "/home/vic/bib/pdfs/Dessertine.pdf" :CATEGORY "org-noter-property-drawer-bug" :granularity greater-element) #2))) :modified-tick 307 :doc-mode doc-view-mode :display-name "and a headline" :notes-file-path "/home/vic/ordis/org-noter-property-drawer-bug.org" :property-text "/home/vic/bib/pdfs/Dessertine.pdf" :level 1 :num-notes-in-view nil :window-behavior (start scroll) :window-location horizontal-split :doc-split-fraction (0.5 . 0.5) :auto-save-last-location nil :hide-other t :closest-tipping-point 0.3))
  #f(compiled-function () #<bytecode -0x1586bdf3b6d4e43>)()
  apply(#f(compiled-function () #<bytecode -0x1586bdf3b6d4e43>) nil)
  timer-event-handler([t 0 0 50000 nil #f(compiled-function () #<bytecode -0x1586bdf3b6d4e43>) nil idle 0 nil])
```

### Environment
Org mode version 9.6.6 (9.6.6-g176086 @ /home/vic/.emacs.d/straight/build/org/)

**Comment by petermao** [comment]
Is this a common workflow?  Why are you starting org-noter from an empty org file?

I always start from a document (initially), then subsequently from the document or its heading in the notes file.  I'm not that familiar with the `-prefer-root-as-file-level` use case.

**Comment by svictor9** [comment]
I don't know how common it is. I've been an org-noter user for around 3-4 years, but with a different workflow. My note files were created from ebib. At the time I started, org-noter did not allow file-level property drawers at all. So they had to have one inital headline. This still works.

Now I'm starting to use org-roam, and org-roam-bibtex. Org-roam-bibtex has an option to create a note file for a reference which has no note. This is roughly an empty file, with only a `#+title:` line and a file-level property drawer. It seems logical to start `org-noter` from there. The described behavior then occurs.  It is for the sake of simplicity that I reproduced and described it from an empty file. 

Whatever I set for `-prefer-root-as-file-level`, the `:NOTER_DOCUMENT:` property gets added to the file-level drawer. This is what I want, but I'm a bit surprised that the option doesn't seem to change anything.

Is my understanding correct that a file with contents like those I provided should be a legit org-noter file (whatever the user's workflow is)? 
Is there another way to use file-level property drawers, or is it something that does not work at the moment?

**Comment by petermao** [comment]
PR #39 that @dmitrym0 has been working on should smooth the way for org-roam integration.  I don't use org-roam (yet) so the workflow is a bit mysterious to me still.

If you're not using `org-noter` with stock custom variables, can you share with us the ones that you've changed?  Also, if you use `org-noter-pdftools`, be sure to mention that.  It's a separate package that we don't maintain.

**Comment by petermao** [comment]
I just spent an hour or so trying to figure out your "point at `point-min`" bug (using our `org-note-with-emacs-basic-test`, which provides a sandboxed emacs session).  I get an error, too, but the backtrace looks different.  I tried to pin down exactly where in the code it's failing, and I can't find it!  Whenever I find the failing function, I restart and step into it, and it runs cleanly.

I was even able to get it to bring up a session and take notes on a pdf.  The backtrace is surprisingly unhelpful, or I just don't know how to use it properly.

**Comment by svictor9** [comment]
I reproduced the error with just `emacs -Q`. More precisely, 
1. `emacs -Q` 
2. load `straight` and `use-package` bootstrap 
3.  `(use-package pdf-tools) (use-package org-noter)`
With this, running `org-noter` in the minimal stub file which I provided fails. Can you reproduce it on your side ?

**Comment by petermao** [comment]
Yes, I was able to reproduce it yesterday.  Please try out the PR #39 branch.

I need some time to think about how to address this issue, which at its root is a "new workflow" problem.  At some point, we have to balance user support with package complexity and maintainabiity.  The Emacs "way" of course, if for everyone to do things in the way that suits them the best.  In order to support that we may have to reconsider the underpinnings of this package.

**Comment by svictor9** [comment]
Thanks for the pointer to PR #39 It still looks a bit fresh and experimental to me. I don't understand all the implications of the code there. 

Please let me stress that the problem which I describe is not linked to `org-roam` in any way. 

In emacs -Q with just `pdf-tools` and `org-noter` loaded, I get the described behavior:
1. create an empty org-file
2. launch `org-noter` from there. Give it a document to annonotate
3. Create a note
4. close the `org-noter` session ("q" on the pdf file window)
5. relaunch the `org-noter` session from the org file 

This results in the described error.    

I don't understand how this is a new workflow, but if it is, it is solely org-noter's workflow. Org-noter creates a file that it can't subsequently interpret. 

As you suggest above, one might indeed start from the pdf file and create the note from there. But `org-noter` has always allowed for the reverse behavior as well, even in the early times when it did not know about file-level properties. This is how I've been using it for the past 4 years. Isn't this bug a regression then?

**Comment by petermao** [comment]
>     3. Create a note
When I create a note **using one of org-noter's functions**, I have no problem relaunching the session; however, if I make a heading with no corresponding `PROPERTIES` drawer with org-noter info, then things don't work so well.

Do you still mean this? (quoting from your OP):
>     3. create a headline (not necessarily an org-noter one) beneath the property drawer

So in its current state, the top headline does need to be a proper org-noter note.

>  I don't understand how this is a new workflow, but if it is, it is solely org-noter's workflow. 
Sorry, I was under the impression that the workflow in the OP was a new-to-you workflow.  If you do need to have a non-org-noter headline for your step 3, I suggest that you bisect the commit history (magit's git bisect feature works pretty nicely) and pinpoint the commit where things stop working for you.  Then we would know who broke your workflow and have some idea of what to do about it.

**Comment by dmitrym0** [comment]
> PR #39 that @dmitrym0 has been working on should smooth the way for org-roam integration. I don't use org-roam (yet) so the workflow is a bit mysterious to me still.

I want to clarify that org-roam integration still requires a top level headline for `:NOTER_DOCUMENT:` property.  There are no changes to core org-noter functionality. I was not aware that file level properties were supported. I'd like to keep the core as simple as possible.
