### ISSUE TITLE
[Feature suggestion] Taking notes on web page

### ISSUE THREAD

**Issue by CyberFox001** [org-noter/org-noter#60]
Hello,

First, a big tank to everyone who work on org-noter. It's a very greate tool.

With org-noter, we can already use PDF and Epub. But sadly, not all web page can be converted easily to one of these formats. 
A lot of time, I cannot use org-noter to take note from a web page.

A great feature could be the possibility to take notes, with Org-noter, on a web page.

But I don't know what could be the best way to do it:
- A web browser plugin to let Org-noter control it from Emacs ?
- An Emacs command, and an Org-mode attach action, to download and convert the webpage to a format supported by Org-noter  ?

Maybe I could help on this.

**Comment by dmitrym0** [comment]
I've been toying with this idea for a little while. My approach has been to convert a web page to pdf since this is supported by org-noter. I'd love to use something like [readability.js](https://github.com/mozilla/readability) to extract the main content of the webpage, but I haven't gotten there yet.

**Comment by daraul** [comment]
My idea was a browser extension that uses text-fragments stored in an org-file -- extra points if it can highlight/navigate to those annotations on the browser window. That doesn't involve org-noter though.

Org-noter might only be involved to open the page in your browser, and (maybe, somehow, idk how) activate the extension to highlight your annotations on the page. That doesn't seem like much of a value add to justify the work, though; I think that most of the time annotation work would begin in the browser itself. 

- https://caniuse.com/mdn-html_elements_a_text_fragments

**Comment by PhDyellow** [comment]
If you want to take notes on websites that are largely text and can be displayed in EWW, then https://nobiot.github.io/org-remark/#Highlight-and-Annotate-Websites may be relevant. 

My rough understanding is that org-noter targets pdf files, and org-remark targets text files, so I use both.

**Comment by CyberFox001** [comment]
Thank you for all the suggestions.
