### ISSUE TITLE
Org 9.7-pre issues: Error running timer: (error "‘org-element-at-point’ cannot be used in non-Org buffer #<buffer filename.pdf> (pdf-view-mode)")

### ISSUE THREAD

**Issue by petermao** [org-noter/org-noter#61]
Starting from this commit in org-mode (2023-08-18 01:11)
`f1359546a @ org-element-at-point: Throw an error when not in org-mode`

Probably our problem to deal with.  This is a placeholder so I can dig into it when I have some time.

**Comment by dmitrym0** [comment]
I have a fix for this one I need to push. Essentially needs to be executed in the context of the notes buffer, not the document buffer.

**Comment by dmitrym0** [comment]
@petermao I pushed a [commit](https://github.com/org-noter/org-noter/commit/27399526aab9f5c61d2a02b7ca25a46c27d3682c) that should fix it.

**Comment by petermao** [comment]
Awesome -- I'm back to a `wrong-type-argument...`  I'll test the code against other versions of Org.  If it doesn't add any problems, then we should merge it into the master branch.

**Comment by dmitrym0** [comment]
> Awesome -- I'm back to a `wrong-type-argument...` I'll test the code against other versions of Org. If it doesn't add any problems, then we should merge it into the master branch.

I’ve yet to dig into the straight.el fix. How does package management happen without use-package or straight.el? What do you use Peter? Surely there’s a way to update org between emacs version updates..

**Comment by petermao** [comment]
At the top of my init file, I have (modified for your case):
```
(add-to-list 'load-path "~/workspace/org-mode/lisp")
(require 'org)
```
You can do about the same for `org-noter`, but `pdf-tools` is a bear -- it has a lot of dependencies and there isn't a single `require` argument that loads everything needed.

For these quick bisection tests, I've been using my init, not the sandboxed one, and not even `emacs -Q`.  I'm pretty sure I'm close enough to "stock" that the results are representative.

**Comment by petermao** [comment]
Also, see https://github.com/org-noter/org-noter/commit/27399526aab9f5c61d2a02b7ca25a46c27d3682c#commitcomment-125618987.  The fix you put in, though innocuous-looking, increases navigation time by 50%.

**Comment by yantar92** [comment]
Peter Mao ***@***.***> writes:

> Also, see https://github.com/org-noter/org-noter/commit/27399526aab9f5c61d2a02b7ca25a46c27d3682c#commitcomment-125618987.  The fix you put in, though innocuous-looking, increases navigation time by 50%.

That's expected - previously that branch of code did nothing because it
was not in Org buffer. Not it does the intended work. Hence taking CPU
time to perform it.

There is nothing wrong with that commit per se, but an extra
`org-noter--parse-root' (AFAIU) is not free.

-- 
Ihor Radchenko // yantar92,
Org mode contributor,
Learn more about Org mode at <https://orgmode.org/>.
Support Org development at <https://liberapay.com/org-mode>,
or support my work at <https://liberapay.com/yantar92>

**Comment by petermao** [comment]
@yantar92, thanks for the explanation.  I'll take a closer look at that section of code.  Maybe better to excise it, but that will require some time to sort out.

**Comment by petermao** [comment]
Maybe I have this one whupped.
