### ISSUE TITLE
how to disable the navigation function

### ISSUE THREAD

**Issue by perfectkaki** [org-noter/org-noter#65]
Sometimes I need to scroll the pdf and keep the org file unmoved.

I have tried setting the [org-noter-closest-tipping-point] to -1.
It keeps the org file unmoved, but showing the err.
And often it freezes emacs about 0.5s when scrolling pages.

![image](https://github.com/org-noter/org-noter/assets/70356424/7c469e79-16a0-41e5-9105-13f1b81a40ca)

**Comment by petermao** [comment]
"tipping point" is one of the concepts in org-noter that I've never understood.  It's been part of the code from very early on, but the documentation doesn't totally make sense to me.

That said, I understand your need to scroll the pdf without syncing the notes, but tipping point may not be the right thing to tweak.  Also, the entire point of `org-noter` is to have your notes synced to your document.

Does your notes file typically contain the notes for several documents or just one?  Do you use indirect buffers (default `org-noter` setup)?  I usually run several docs per notes file, and I can get a non-syncing look into the notes file by opening the direct notes file.  In this case I would split the notes window and have document on the left, indirect notes (syncing) in the upper right, and direct notes (non-syncing) in the lower right.

**Comment by petermao** [comment]
Another way is to put your note in a non-org-noter heading under the title heading, or to write those notes under the title heading without a subheading.  Those won't fold.  LMK if this is a sufficient solution for you

**Comment by perfectkaki** [comment]
Thanks for your advice. I think the [split method] is the best answer for so far. 
If I find other way, I'll share here.
