### ISSUE TITLE
Can't delete properties

### ISSUE THREAD

**Issue by AdelleBernal** [org-noter/org-noter#80]
### Description
I cannot delete properties under the heading where I created nots
#### Steps to Reproduce
Start org-noter in OrgMode buffer
Once finished, kill the session and try to delete the notes
I managed to delete the notes except
:PROPERTIES:
:NOTER_DOCUMENT: papers/Vander.pdf
:END:

It tells me "Text is read-only"

### Environment
MacOs Mojave
Org mode version 9.5.5 (release_9.5.5 @ /Applications/Emacs.app/Contents/Resources/lisp/org/)

**Comment by dmitrym0** [comment]
Hello @AdelleBernal,

I'm not able to reproduce this locally. I'm running emacs 29 and org-mode 9.7-pre.

You can try `M-x read-only-mode`, but I'm not sure why your buffer is read only. Possibly your local config is causing this issue.

**Comment by AdelleBernal** [comment]
Let's close this issue, you probably are right if you are not having my issue. Thanks.
