### ISSUE TITLE
Error: "resource key too long" when opening org-noter from long headings

### ISSUE THREAD

**Issue by ChanderG** [org-noter/org-noter#82]
#### Steps to Reproduce

This is not a mistake of org-noter, but nevertheless impacts org-noter users. When opening org-noter from an org-mode heading, if the title is too long, the org-noter frame does not open. Instead an error is thrown: "resource key too long".

This is because `make-frame` called here https://github.com/org-noter/org-noter/blob/9e4f57957b8f54db20a4e13bf8d6b32e004ab3e8/org-noter-core.el#L699 has a limitation on title length (at least in my setup).

A minimal reproducible example that errors out is this following:
```
(make-frame `((name . ,(make-string 105 ?x))))
```
(On my system, numbers below 105 work fine, which is a limit found using binary search).

Specifically, the stack trace ends at `x-create-frame-with-faces` where the `x-resource-name` is set to the title. I don't know if this is a problem only on Linux. Actually, this function name confuses me a bit, since I am on Wayland with the pgtk build. Not sure if the "x" in this function refers to "X11" or something else?

In any case:
1. Trivial solution is to use shorter headings.
2. If this is a problem that occurs on all platforms (not just Linux X11/Wayland), maybe better to truncate the heading to a reasonable size before creating the frame.

#### Expected Results

Org-noter opens up a new frame with the pdf/notes.

#### Actual Results

Error "resource key too long" is thrown.

### Environment

Org 9.6.15 (not relevant)

**Comment by petermao** [comment]
I'm on GNU/Linux with X11 (ubuntu 20.04).  I'm not seeing any problems with either a 215-character length title or note heading.  Thank you for the minimal example.  That works fine on my system as well.  I can check OSX next week.  I don't have a Wayland system to test on.

**Comment by snrubthinks** [comment]
I can reproduce this issue on sway (wayland), using the pgtk emacs version (30.2). I.e. with the minimal example above:

(make-frame `((name . ,(make-string 105 ?x))))

and with org-noter in general.
