### ISSUE TITLE
Checking for base packages only applies to default package manager

### ISSUE THREAD

**Issue by Elilif** [org-noter/org-noter#9]
When using git submodule or other package managers, the checks in 2ccbf1cdbe74b14fd1f0de8b848ec392f0d37d4a will fail.

**Comment by petermao** [comment]
True.  This is alluded to in issue #5, and elsewhere by @pobermei.

I can add some code to check if the relevant packages are loaded, but I don't know how to determine if a package is available but not yet loaded, other than when the package shows up in `package-alist`.  A solution to this issue would be welcomed.

**Comment by dmitrym0** [comment]
@Elilif what package manager do you use and how does it fail?

**Comment by petermao** [comment]
If, for example, the user uses nov.el, but nov is not in `package-alist`, then org noter will not run `(require 'nov)` and the ATTENTION message will show up.  So the user has to do that separately.  Annoying but not fatal.

If we blindly run `(require 'nov)`, then in the case where the user does not have nov.el, the org-noter will crash.   Worse than annoying.

@Elilif could you write up an example and submit it as a PR?

**Comment by dmitrym0** [comment]
Ahh I see. This is actually happening to me with `straight.el` because it doesn't use `package-alist`.

This is what condition-case could look like:

```
(condition-case nil
    (require 'package-that-doesnot-exist)
  (error (message "ATTENTION: pakackage-that-doesnot-exist is required for correct operation")))
```

I can take of this next week.
