### ISSUE TITLE
org-noter not using absolute paths

### ISSUE THREAD

**Issue by scfrank-pri** [org-noter/org-noter#91]
When creating a new org-noter note for a PDF file located in, e.g., ~/Downloads, I am asked for the location of the note (somewhere else ...), but in the note itself NOTER_DOCUMENT only links back to the document in a relative path. Example
```* 0c9e5875c03595bdee5d990913efb030  
:PROPERTIES:  
:NOTER_DOCUMENT: ../../../Downloads/0c9e5875c03595bdee5d990913efb030.pdf  
:END:  
``` 
But I have configured
`'(org-link-file-path-type 'absolute)`
Why is this not respected? 
Or: put it differently: How can I get org-noter to use absolute paths?

**Comment by petermao** [comment]
I agree that we should support absolute paths, but we took over the code as-is a few years ago, and never interacted with the original author.

I'm not sure that the NOTER_DOCUMENT property is truly an org-link -- I'd have to look into the code to see how the property is used to make that judgement.

**Comment by dmitrym0** [comment]
The `NOTER_DOCUMENT` entry is a property not a link. Relative paths is just how it works. Why do you want an absolute path @scfrank-pri ?

**Comment by scfrank-pri** [comment]
Short answer: If I move notes around, the absolute path can be more easily edited. I thought that the entry is a link.

**Comment by petermao** [comment]
Not sure if this is satisfactory for your use case, but take a look at `org-noter-enable-sync-renames`.

**Comment by scfrank-pri** [comment]
Interesting! I did not know about `org-noter-enable-update-renames` (it's called like this in my org-noter version) and, incidentally, also discovered `org-noter-enable-org-roam-integration`. Still need to figure out how to use `org-noter-enable-update-renames`, but it should be useful. Thanks for the hint.

**Comment by petermao** [comment]
You are right -- it is `org-noter-enable-update-renames`.  When you call this function, it adds advice to `dired-rename-file` to update the NOTER_DOCUMENT property when you rename (or move) either the document or the notes file.  As with many thing, we are conservative about changing defaults, but that also means that noone finds out about new features unless they read the docs or bring up related issues.
