### ISSUE TITLE
Missing dependency org-roam in modules/org-noter-org-roam.el

### ISSUE THREAD

**Issue by jian-lin** [org-noter/org-noter#92]
### Description

`org-noter-org-roam.el` [requires] `org-roam-node` which is part of `org-roam`.  However, this dependency is not declared anywhere.  On MELPA, `org-roam` is [not] listed as a dependency of `org-noter`.  This generates compilation errors like

```console
Error: file-missing ("/nix/store/qxhwb17ahzxpc2fn6a9mfqyi80jgv61v-emacs-org-noter-20240509.1756/share/emacs/site-lisp/elpa/org-noter-20240509.1756/modules/org-noter-org-roam.el" "Cannot open load file" "No such file or directory" "org-roam-node") 
```

ref: https://github.com/NixOS/nixpkgs/issues/335442

[requires]: https://github.com/org-noter/org-noter/blob/6f292d7f1efb11222c09f3a91c902ea6e4dbfa33/modules/org-noter-org-roam.el#L27
[not]: https://melpa.org/#/org-noter

**Comment by petermao** [comment]
org-roam is not a true dependency of org-noter.  It is only required if you want to make use of the org-roam features.

At it's core, org-noter only requires doc-view, which is part of emacs.  Most of our develpment since taking over maintenance has been to spruce up the pdf-tools features.

**Comment by jian-lin** [comment]
I notice that another optional dependency `nov` does not generate a compilation error.  What about using that [trick] for org-roam?

[trick]: https://github.com/org-noter/org-noter/blob/6f292d7f1efb11222c09f3a91c902ea6e4dbfa33/modules/org-noter-nov.el#L28-L34

**Comment by petermao** [comment]
We can do something about the documentation, but org-roam, pdf-tools, nov-mode, and djvu-mode are all optional.  As such, it is up to the user to fill in those soft-dependencies as they desire.

**Comment by petermao** [comment]
> I notice that another optional dependency `nov` does not generate a compilation error. What about using that [trick](https://github.com/org-noter/org-noter/blob/6f292d7f1efb11222c09f3a91c902ea6e4dbfa33/modules/org-noter-nov.el#L28-L34) for org-roam?

@dmitrym0 ?

**Comment by jian-lin** [comment]
FYI, MELPA [suggests] creating separate MELAP packages to handle optional dependencies.  [Here] is an example.  Note that it breaks backward compatibility though.

[Here]: https://github.com/melpa/melpa/blob/master/README.md#example-multiple-packages-in-one-repository
[suggests]: https://github.com/melpa/melpa/blob/bfa04bef05bdeab1a097cb5204263ee9078f83a9/CONTRIBUTING.org?plain=1#L157-L161

**Comment by dmitrym0** [comment]
Hmm, I wonder why I was never notified of this issue. 

org-roam is indeed an optional dependency, I'll make it happen.

**Comment by dmitrym0** [comment]
Created #95. I need to test it without my custom config. 

Btw @petermao I think the second repetition of `condition-case` is not necessary. According to the docs, `eval-when-compile` is executed both during compile and interpretation time.

**Comment by jian-lin** [comment]
> I think the second repetition of `condition-case` is not necessary. According to the docs, `eval-when-compile` is executed both during compile and interpretation time.

I think it is necessary.

Quoting Elisp manual:
>  -- Macro: eval-when-compile body...
     This form marks BODY to be evaluated at compile time but not when
     the compiled program is loaded.  The result of evaluation by the
     compiler becomes a constant which appears in the compiled program.

I just test that with #95 applied there is no runtime message about missing org-roam.

**Comment by dmitrym0** [comment]
I stand corrected. I’ll add the second part tomorrow.

**Comment by dmitrym0** [comment]
@jian-lin would you mind taking another look? #96 should be ready.

I'm also curious how you test these in isolation?

**Comment by jian-lin** [comment]
> I'm also curious how you test these in isolation?

I use [nix](https://nixos.org/).  Two of its advantages make the test easy.

1. It is easy to apply patches to packages.
2. It is easy to create isolated Emacs with some elisp packages.

<details>
  <summary>default.nix</summary>
  
```nix
let
  nixpkgs = builtins.fetchTarball {
    url = "https://github.com/nixos/nixpkgs/archive/345c263f2f53a3710abe117f28a5cb86d0ba4059.tar.gz";
    sha256 = "1llzyzw7a0jqdn7p3px0sqa35jg24v5pklwxdybwbmbyr2q8cf5j";
  };
  pkgs = import nixpkgs { };
  overlay = final: prev: {
    org-noter = prev.org-noter.overrideAttrs (old: {
      ignoreCompilationError = false;
      patches = old.patches or [ ] ++ [
        (pkgs.fetchpatch {
          name = "pr-95";
          url = "https://github.com/org-noter/org-noter/commit/761c551ecc88fec57e840d346c6af5f5b94591d5.patch";
          hash = "sha256-Diw9DgjANDWu6CBMOlRaihQLOzeAr7VcJPZT579dpYU=";
        })
        (pkgs.fetchpatch {
          name = "pr-96";
          url = "https://github.com/org-noter/org-noter/pull/96/commits/a690166d8f59d5d4215570411809b0c41d48c18d.patch";
          hash = "sha256-y0F1yKHPVQGRUCz0cBIaVJ8Q8Mguri0M9O/nN2bEeco=";
        })
      ];
    });
  };
  emacsPackages = pkgs.emacs.pkgs.overrideScope overlay;
in
{
  # emacs with only org-noter (and its dependencies) installed
  emacs = emacsPackages.withPackages (epkgs: [ epkgs.org-noter ]);
  # org-noter itself, useful for checking build log
  org-noter = emacsPackages.org-noter;
}

```
</details>

With this defeault.nix file, you can build an Emacs with only org-noter (and its dependencies) like this
```console
> nix build --file default.nix emacs
```
Then do the test
```console
> ./result/bin/emacs --batch --init-directory=init-tmp-dir --eval="(progn (require 'org-noter) (org-noter-enable-org-roam-integration))"
```

With only the first patch (#95) applied, the output is
```console
Loading /nix/store/qpydf23li3b7kciidc6x7drw1awz0jlc-emacs-29.4/share/emacs/site-lisp/site-start...
ATTENTION: org-noter-pdf has many featues that depend on the package ‘pdf-tools’
ATTENTION: org-noter-nov needs the package ‘nov’
ATTENTION: org-noter-djvu needs the package ‘djvu’
Loading org-noter-org-roam (native compiled elisp)...
```

With both #96 and #96 applied, the output is
```console
Loading /nix/store/qpydf23li3b7kciidc6x7drw1awz0jlc-emacs-29.4/share/emacs/site-lisp/site-start...
ATTENTION: org-noter-pdf has many featues that depend on the package ‘pdf-tools’
ATTENTION: org-noter-nov needs the package ‘nov’
ATTENTION: org-noter-djvu needs the package ‘djvu’
Loading org-noter-org-roam (native compiled elisp)...
‘org-roam-node is not found. org-noter’s org-roam support requires org-roam to be installed. Please install org-roam.
```

BTW, I discover this issue in our NixOS CI: https://hydra.nixos.org/build/271384989/nixlog/1

**Comment by dmitrym0** [comment]
@jian-lin Thanks for the explanation. I've been eyeing nix for a while maybe it's time to jump in.

I think this is as good as it gets for now. I dont know how to manage optional package dependencies other than what melpa suggests.

**Comment by jian-lin** [comment]
> I think this is as good as it gets for now

Yeah, I think so.  Let's close this issue.  Thanks!
