### ISSUE TITLE
Clarifying how highlighting should work

### ISSUE THREAD

**Issue by purplefishies** [org-noter/org-noter#98]
Hi

I'm able to install and use org noter equally well in Linux and Cygwin. However on each platform I can't reproduce what Dimitri does in the videos. I can create a note that correspond to a highlighted region in the PDF, but when I revisit that location the highlights aren't there. 

I took some time to learn about pdftools and pdfview mode and found that I can nicely add highlighted regions to my PDF on both platforms. 

Is this just a configuration issue where adding a note doesn't automatically leave a highlighted region in the original PDF ? I couldn't find a configuration that lets me recreate the YouTube video.

**Comment by purplefishies** [comment]
Sorry, 

I deleted both packages and then reinstalled them using the latest/ greatest from melpa and don't see the problems that I described

**Comment by petermao** [comment]
the best issues are the ones that resolve themselves ;)
